# Generated by Django 4.2.5 on 2023-10-08 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('upload_date', models.DateField(default=datetime.date(2023, 10, 8))),
                ('program', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('Cyber Security', 'Cyber Security'), ('Biochemistry', 'Biochemistry'), ('Industrial Chemistry', 'Industrial Chemistry'), ('Business Administration', 'Business Administration'), ('Mass Communication', 'Mass Communication'), ('Criminology', 'Criminology'), ('Microbiology', 'Microbiology'), ('Economics', 'Economics'), ('Accounting', 'Accounting')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 10, 8, 18, 8, 34, 129862, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('matric_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('program', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('Cyber Security', 'Cyber Security'), ('Biochemistry', 'Biochemistry'), ('Industrial Chemistry', 'Industrial Chemistry'), ('Business Administration', 'Business Administration'), ('Mass Communication', 'Mass Communication'), ('Criminology', 'Criminology'), ('Microbiology', 'Microbiology'), ('Economics', 'Economics'), ('Accounting', 'Accounting')], max_length=50)),
                ('level', models.CharField(max_length=3)),
                ('enrollment_date', models.DateField(default=datetime.date(2023, 10, 8))),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=500)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 10, 8, 18, 8, 34, 129862, tzinfo=datetime.timezone.utc))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.student')),
            ],
        ),
    ]
