# Generated by Django 4.2.5 on 2023-10-08 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='url',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 19, 53, 32, 29671, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 19, 53, 32, 29671, tzinfo=datetime.timezone.utc)),
        ),
    ]
